/**
 * Fix User IDs: Updates public."User" table and all FK references
 * to match the UUIDs generated by Supabase Auth.
 *
 * Run: npx tsx fix-user-ids.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Mapping: oldId (seed placeholder) → newId (Supabase Auth UUID)
const ID_MAP: Record<string, string> = {
  'aaaaaaaa-0000-0000-0000-000000000001': '8b176011-ef24-4ca2-b7f3-89ae5c06a885', // admin@emt.com.br
  'aaaaaaaa-0000-0000-0000-000000000002': '15cb4fbb-67e8-4dbc-85b9-4b3ad040b5a7', // engenheiro@emt.com.br
  'aaaaaaaa-0000-0000-0000-000000000003': '0be587f6-2fc8-4343-91c8-eee919ce501c', // campo@emt.com.br
};

async function main() {
  console.log('🔧 Corrigindo IDs de usuário...\n');

  // Use session_replication_role = 'replica' to disable FK trigger checks.
  // This is the PostgreSQL way to temporarily bypass NON DEFERRABLE constraints.
  await prisma.$transaction(async (tx) => {
    await tx.$executeRawUnsafe(`SET session_replication_role = 'replica'`);

    for (const [oldId, newId] of Object.entries(ID_MAP)) {
      console.log(`  ${oldId.slice(0, 8)}... → ${newId.slice(0, 8)}...`);

      // Update all FK columns that reference User.id
      await tx.$executeRawUnsafe(`UPDATE "DailyReport"      SET "userId"      = $1 WHERE "userId"      = $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "PurchaseRequest"  SET "requesterId" = $1 WHERE "requesterId" = $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "PurchaseRequest"  SET "approverId"  = $1 WHERE "approverId"  = $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "GoodsReceipt"     SET "receivedById"= $1 WHERE "receivedById"= $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "StockMovement"    SET "userId"      = $1 WHERE "userId"      = $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "Transfer"         SET "userId"      = $1 WHERE "userId"      = $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "Measurement"      SET "measuredById"= $1 WHERE "measuredById"= $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "Measurement"      SET "approvedById"= $1 WHERE "approvedById"= $2`, newId, oldId);
      await tx.$executeRawUnsafe(`UPDATE "Measurement"      SET "rejectedById"= $1 WHERE "rejectedById"= $2`, newId, oldId);

      // Update the PK last (deferred constraints allow this)
      await tx.$executeRawUnsafe(`UPDATE "User" SET "id" = $1 WHERE "id" = $2`, newId, oldId);

      console.log(`  ✅ OK`);
    }
  });

  console.log('\n🎉 IDs atualizados com sucesso!');
  console.log('\nUsuários prontos para login:');
  console.log('  • admin@emt.com.br      / Demo@123  (ADMIN)');
  console.log('  • engenheiro@emt.com.br / Demo@123  (ENGINEER)');
  console.log('  • campo@emt.com.br      / Demo@123  (FIELD)');
}

main()
  .catch((e) => {
    console.error('❌ Erro:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
